gerrit-translator-cdevents : Plugin implementation to translate branch and repository events
cdevents/gerrit-translator pull request #1
Opened 2024-03-19 16:28 UTC by rjalander

Implementation of  `EventTranslator` interface that is exposed by [CDEvents Webhook Adapter](https://github.com/cdevents/webhook-adapter/pull/1) to translate gerrit events into CDEvents.
This PR includes the changes to translate below Project and Branch related gerrit events into CDEvents, with the mappings as below
| CDEvent Type  | Gerrit Event Type  |
| :------------ |:-------------------|
| dev.cdevents.repository.created| project-created |
|  dev.cdevents.repository.modified   | project-head-updated    |
| dev.cdevents.branch.created   |  ref-updated     |
| dev.cdevents.branch.deleted |   ref-updated    |

Note: Implementation as per the design RFC: [gerrit-translator-cdevents-plugin](https://github.com/cdevents/community/blob/2cdbb0120d8f347774bcfcec172915383e855baa/rfc/cdevents-translator.md#implement-gerrit-translator-cdevents-plugin-1) and mapping events [gerrit-cdevents](https://github.com/cdevents/community/blob/2cdbb0120d8f347774bcfcec172915383e855baa/rfc/gerrit-cdevents.md)

Signed-off-by: Jalander Ramagiri @rjalander

2024-03-20 14:59 UTC, adamkenihan approved these changes

2024-04-11 20:15 UTC, xibz requested changes
@rjalander This looks like a good start. I have some questions and some ideas on how to make this a little more scalable.

2024-04-11 20:15 UTC, xibz commented on README.md
> +go build -o gerrit-translator-cdevents ./pkg/
Do we have a `Makefile`? This is the default build tool that's used by Golang. So if not, let's add one

2024-04-11 20:15 UTC, xibz commented on pkg/gerrit/create_cdevents.go
> +		return "", err
One thing that might be appropriate to do is wrap these in our own `Error`. I think a little digging is required here, but what do the errors look like when returned from the SDK?

For instance, if the error that is returned is something like `error: pipe broken` than that's not too useful. Wrapping these errors with something that provides more context may be necessary

Right now we have two repos: 

The plugin webhook adapter thingy and translator(s).

The webhook adapter can provide a set of `Error` types that can be wrapped, and I think that would at least give some guidance on how the adapter should handle such errors, e.g. should we return a proper status code based on error type for example.

This will require some design, but I think it's an important call out and consideration.

2024-04-11 20:15 UTC, xibz commented on pkg/gerrit/create_cdevents.go
> +	log.Println("Creating CDEvent RepositoryCreatedEvent")
While, `log` is generally a good starting place for debugging, it really isn't an adequate logger for an application. Take a look at, https://github.com/uber-go/zap

2024-04-11 20:15 UTC, xibz commented on pkg/gerrit/create_cdevents.go
> +func (projectHeadUpdated *ProjectHeadUpdated) RepositoryModifiedCDEvent() (string, error) {
Hmm, this seems a little odd, and I was thinking of a much different approach. Can you schedule a meeting with me? I want to go over some design consideration here

2024-04-22 14:44 UTC, rjalander commented on README.md
> +go build -o gerrit-translator-cdevents ./pkg/
Added a `Makefile`, to build and clean

2024-04-22 14:46 UTC, rjalander commented on pkg/gerrit/create_cdevents.go
> +		return "", err
Will create an issue for handling these error scenarios and discuss design considerations here.

2024-04-22 14:46 UTC, rjalander commented on pkg/gerrit/create_cdevents.go
> +	log.Println("Creating CDEvent RepositoryCreatedEvent")
updated to use zap logger in this plugin implementation

2024-05-01 01:40 UTC, xibz approved these changes, later dismissed
Had just two comments, but I think we still need to go over the implementation of the go tags. It'll make this much easier in the future. Can you schedule something for this week?

2024-05-01 01:40 UTC, xibz commented on .github/workflows/ci.yml
> +name: CI
Can we make this a separate PR? There's a lot happening in here, so I want to reduce the size a little bit to something a little more atomic.

2024-05-01 01:40 UTC, xibz commented on pkg/gerrit/logger.go
> +func InitLogger() {
There's an `init` method in Go. I think this is one of the use cases I think that it might work well for. You don't need to call `init`, it'll be automatically called upon application starting

2024-05-01 01:41 UTC, xibz requested changes
requesting some changes

2024-06-07 17:24 UTC, xibz reviewed
Just adding a comment about our prior meeting with Jalander and Andrew.

The goal is to utilize `copygen` or some library that supports easy copying of structs without needing to manually write them ourselves.

There was some concerns around perfection and feature creep, so we decided that if we are unable to get struct tags in the go sdk by mid July, we will go ahead with the duplicated copying logic until struct tags exist.

2024-06-12 14:27 UTC, rjalander commented
> Just adding a comment about our prior meeting with Jalander and Andrew.
> 
> The goal is to utilize `copygen` or some library that supports easy copying of structs without needing to manually write them ourselves.
> 
> There was some concerns around perfection and feature creep, so we decided that if we are unable to get struct tags in the go sdk by mid July, we will go ahead with the duplicated copying logic until struct tags exist.

created this PR https://github.com/cdevents/sdk-go/pull/82 to support `copygen` for go-sdk

2024-06-29 02:09 UTC, xibz approved these changes
Thanks for all the changes @rjalander. I will go ahead and approve this. The goal, however, is to eventually use some copier library to make it easy for translators to be developed. I will create a separate issue for that.

2024-07-01 13:05 UTC, rjalander commented
> Thanks for all the changes @rjalander. I will go ahead and approve this. The goal, however, is to eventually use some copier library to make it easy for translators to be developed. I will create a separate issue for that.

Thanks @xibz, We will address this issue and initiate a separate pull request to implement the copying of metadata utilizing a designated copier library.

@afrittoli, could you please review this PR and approve it if there are no comments?

2024-07-01 14:31 UTC, afrittoli commented on .github/workflows/ci.yml
> +name: CI
Generally I agree on smaller PRs, but in this case, merging CI first would mean there is nothing to test and merging CI after some code is in the repo would mean that the first code was untested. 
At this stage, neither is really problematic, but also I'm not sure it's worth the extra work of splitting the PR.

2024-07-01 14:32 UTC, afrittoli commented on README.md
> +### How to run locally
The text below describes how to build it, not how to run it

2024-07-01 14:59 UTC, afrittoli reviewed
One thing that I noticed is that the plugin here returns CDEvents as JSON. 

Currently the [`AsCloudEvent`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L101) function takes a CDEvent reader object as input, and there is no obvious way to send a JSON CDEvent as CloudEvent other than parsing it back into an object and using `AsCloudEvent`.

Perhaps we'll need a new method in the SDK. or a different interface here

2024-07-01 14:59 UTC, afrittoli commented on go.mod
> +	github.com/cdevents/sdk-go v0.3.2
v0.4 will be out soon,  but no need to wait for it.

2024-07-01 16:44 UTC, rjalander commented
> One thing that I noticed is that the plugin here returns CDEvents as JSON.
> 
> Currently the [`AsCloudEvent`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L101) function takes a CDEvent reader object as input, and there is no obvious way to send a JSON CDEvent as CloudEvent other than parsing it back into an object and using `AsCloudEvent`.
> 
> Perhaps we'll need a new method in the SDK. or a different interface here

I tried using an interface which accepts `cdevent` object as a returned value instead of `cdevent` JSON string in the webhook-adapter, but that has some difficulties in generating grpc client code using protoc-gen for custom datatypes.
So using JSON string as a response for this interface, https://github.com/cdevents/webhook-adapter/blob/main/pkg/proto/translator.proto#L37

And in `webhook-adapter` the received `cdevent` JSON string will be converted to `cdevent` object using [NewFromJsonString(event string) (CDEvent, error)](https://github.com/cdevents/webhook-adapter/blob/main/pkg/cdevents/helper.go#L76), but looks like this method is replaced in the main go-sdk (need to use differently once webhook-adapter upgraded to v0.4 sdk)

2024-07-01 16:47 UTC, rjalander commented on README.md
> +### How to run locally
updated to `How to build locally`

2024-07-02 09:10 UTC, afrittoli commented
> > One thing that I noticed is that the plugin here returns CDEvents as JSON.
> > Currently the [`AsCloudEvent`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L101) function takes a CDEvent reader object as input, and there is no obvious way to send a JSON CDEvent as CloudEvent other than parsing it back into an object and using `AsCloudEvent`.
> > Perhaps we'll need a new method in the SDK. or a different interface here
> 
> I tried using an interface which accepts `cdevent` object as a returned value instead of `cdevent` JSON string in the webhook-adapter, but that has some difficulties in generating grpc client code using protoc-gen for custom datatypes. So using JSON string as a response for this interface, https://github.com/cdevents/webhook-adapter/blob/main/pkg/proto/translator.proto#L37
> 
> And in `webhook-adapter` the received `cdevent` JSON string will be converted to `cdevent` object using [NewFromJsonString(event string) (CDEvent, error)](https://github.com/cdevents/webhook-adapter/blob/main/pkg/cdevents/helper.go#L76), but looks like this method is replaced in the main go-sdk (need to use differently once webhook-adapter upgraded to v0.4 sdk)

I could not avoid having the `NewFromJsonString` method being version specific - so in the new SDK you have one version for v0.3 and one for [v0.4](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/v04/docs.go#L483C6-L483C23).

There is a [`NewFromJsonBytes`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L171) method that works with golang generics and can be used across spec versions, but the version specific `NewFromJsonString` is more convenient to use.

2024-07-02 15:48 UTC, rjalander commented
> > > One thing that I noticed is that the plugin here returns CDEvents as JSON.
> > > Currently the [`AsCloudEvent`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L101) function takes a CDEvent reader object as input, and there is no obvious way to send a JSON CDEvent as CloudEvent other than parsing it back into an object and using `AsCloudEvent`.
> > > Perhaps we'll need a new method in the SDK. or a different interface here
> > 
> > 
> > I tried using an interface which accepts `cdevent` object as a returned value instead of `cdevent` JSON string in the webhook-adapter, but that has some difficulties in generating grpc client code using protoc-gen for custom datatypes. So using JSON string as a response for this interface, https://github.com/cdevents/webhook-adapter/blob/main/pkg/proto/translator.proto#L37
> > And in `webhook-adapter` the received `cdevent` JSON string will be converted to `cdevent` object using [NewFromJsonString(event string) (CDEvent, error)](https://github.com/cdevents/webhook-adapter/blob/main/pkg/cdevents/helper.go#L76), but looks like this method is replaced in the main go-sdk (need to use differently once webhook-adapter upgraded to v0.4 sdk)
> 
> I could not avoid having the `NewFromJsonString` method being version specific - so in the new SDK you have one version for v0.3 and one for [v0.4](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/v04/docs.go#L483C6-L483C23).
> 
> There is a [`NewFromJsonBytes`](https://github.com/cdevents/sdk-go/blob/9ac1c5642fbe1a0812e2a1a929d7985d500cd0e3/pkg/api/bindings.go#L171) method that works with golang generics and can be used across spec versions, but the version specific `NewFromJsonString` is more convenient to use.

Ok, will use the same function `NewFromJsonString` after `webhook-adaper` is upgraded to v0.4

2024-07-03 10:16 UTC, rjalander commented
@afrittoli, could you please approve it if there are no other comments?

2024-07-03 10:30 UTC, afrittoli commented on pkg/gerrit/create_cdevents.go
> +		return "", err
@rjalander could you share a link to the issue?

2024-07-03 10:30 UTC, afrittoli approved these changes

2024-07-03 10:35 UTC, rjalander commented on pkg/gerrit/create_cdevents.go
> +		return "", err
https://github.com/cdevents/webhook-adapter/issues/5

2024-07-03 10:41 UTC, adamkenihan approved these changes

2024-07-03 10:42 UTC, merged